language: java

cache:
  directories:
  - $HOME/.m2
services:
  - mysql

jdk:
  - oraclejdk8
mysql:
  database: db_blog
  username: root
  password :
  encoding: utf8
install:
  - cd ./mcloud-blog
  - mvn clean install -Dmaven.test.skip=true
before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS db_blog;'
script:
  - mvn test -DactiveProfile=ci
after_success:
  - mvn test -DactiveProfile=ci jacoco:report coveralls:report
notifications:
  email:
    - heyuxian.me@gmail.com