language: java

cache:
  directories:
  - $HOME/.m2
services:
  - mysql

jdk:
  - oraclejdk8
mysql:
  database: blackc
  username: root
  password :
  encoding: utf8
install:
  - cd ./mcloud-blog
  - mvn install -Dmaven.test.skip=true
before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS blackc;'
script:
  - mvn test -DactiveProfile=ci
notifications:
  email:
    - heyuxian.me@gmail.com