server:
  port: 8761
spring:
  application:
    name: mcloud-registry
  jmx:
    enabled: false
eureka:
  instance:
    appname: mcloud-registry
    hostname: mcloud-registry.example.com
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"