server:
  port: 80
  servlet:
    context-path: /
spring:
  application:
    name: mcloud-apigw
eureka:
  instance:
    appname: mcloud-apigw
    hostname: mcloud-apigw.example.com
    statusPageUrlPath: ${server.servlet.context-path}actuator/info
    healthCheckUrlPath: ${server.servlet.context-path}actuator/health
    metadata-map:
      management:
        context-path: ${server.servlet.context-path}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    users:
      sensitiveHeaders: Cookie,Set-Cookie
      path: /demo/**
      serviceId: "mcloud-demo"
      stripPrefix: false
oauth2:
  keycloak:
    client:
      client-id: mcloud-demo
      client-secret: 123456
      access-token-uri: http://localhost:8443/auth/realms/mcloud/protocol/openid-connect/token
