server:
  port: 80
  context-path: /apigw
management:
  context-path: /monitoring
  security:
    enabled: false
zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    blog:
      path: /blog/**
      service-id: blog
      stripPrefix: false
    uia:
      path: /uia/**
      service-id: uia
      stripPrefix: false