server:
  context-path: /monitoring
  port: 18080
management:
  security:
    enabled: false
eureka:
  instance:
    hostname: mcloud-monitoring
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: ${server.context-path}/info
    healthCheckUrlPath: ${server.context-path}/health
    metadata-map:
      management:
        context-path: ${server.context-path}
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: mcloud-monitoring
  boot:
    admin:
      routes:
        endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream