server:
  port: 80
logging:
  path: D:\logs
  level: error
spring:
  datasource:
    #TODO 根据每个项目自行设置
    url: jdbc:mysql://localhost/auth_c
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    #TODO 正式环境需修改设置 update->none
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    show-sql: true
  thymeleaf:
    cache: false