server:
  port: 8043
  context-path: /uaa
logging:
  level:
    org.springframework.security: DEBUG
spring:
  datasource:
    #TODO 根据每个项目自行设置
    url: jdbc:mysql://localhost/auth_c
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
      static-path-pattern: /static/**
  jpa:
    #TODO 正式环境需修改设置 update->none
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    show-sql: true
  thymeleaf:
    cache: false