server:
  port: 8761
# 禁用 livereload,否则在同一台机器上启动多个服务时会有端口占用问题
#spring:
#  devtools:
#    livereload:
#      enabled: false
spring:
  application:
    name: mcloud-eureka
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/