language: java

services:
  - mysql

jdk:
  - oraclejdk8

mysql:
  database: db_blog_test
  username: root
  password :
  encoding: utf8

install:
  - mvn install -Dmaven.test.skip=true

before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS db_blog_test;'

script:
  - mvn test -DactiveProfile=ci
after_success:
  - mvn clean test -DactiveProfile=ci jacoco:report coveralls:report
notifications:
  email:
    - heyuxian.me@gmail.com