server:
  port: 8081
  context-path: /blog
logging:
  level:
    org.springframework.security: DEBUG

spring:
  application:
    name: mcloud-blog
  datasource:
    url: jdbc:mysql://localhost/db_blog
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    show-sql: true

security:
  oauth2:
    resource:
      id: blog
      jwt:
        key-uri: http://mcloud-oauth-server:8043/uaa/oauth/token_key

management:
  context-path: /monitoring
  security:
    enabled: false
eureka:
  instance:
    hostname: mcloud-blog
    statusPageUrlPath: ${server.context-path}${management.context-path}/info
    healthCheckUrlPath: ${server.context-path}${management.context-path}/health
    metadata-map:
      management:
        context-path: ${server.context-path}${management.context-path}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

swagger:
  title: MCloud-blog
  description: http://javaroad.me
