blog:
  default:
    page: 1
    size: 10
# 禁用 livereload,否则在同一台机器上启动多个服务时会有端口占用问题
# refer to: https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#using-boot-devtools-livereload
spring:
  devtools:
    livereload:
      enabled: false