server:
  port: 8081
logging:
  path: D:\logs\black-c
  level: error
spring:
  datasource:
    url: jdbc:mysql://localhost/blackc
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    show-sql: true
mcloud:
  client:
    clientId: mcloud-blog
    clientSecret: 123456
    userAuthorizationUri: http://localhost:8043/mcloud/oauth/authorize
    accessTokenUri: http://localhost:8043/mcloud/oauth/token
  resource:
        userInfoUri: http://localhost:8043/mcloud/me
