server:
  port: 8899
  context-path: /uaa
logging:
  level:
    org.springframework.security: DEBUG
spring:
  thymeleaf:
    cache: false
oauth2:
  provider:
    mcloud:
      clientId: mcloud-blog
      clientSecret: 123456
      accessTokenUri: http://localhost:8043/mcloud/oauth/token
      userAuthorizationUri: http://localhost:8043/mcloud/oauth/authorize