server:
  port: 8443
  context-path: /uia
spring:
  thymeleaf:
    cache: false
mcloud:
  oauth2:
    client:
      clientId: mcloud-blog
      clientSecret: 123456
      callback-uri: http://localhost:8443/uia/oauth2/callback
    server:
      accessTokenUri: http://mcloud-oauth-server:8043/uaa/oauth/token
      userAuthorizationUri: http://mcloud-oauth-server:8043/uaa/oauth/authorize

security:
  basic:
    enabled: false
  oauth2:
    resource:
      id: uia
      jwt:
        key-uri: http://mcloud-oauth-server:8043/uaa/oauth/token_key

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    appname: mcloud-uia
    statusPageUrlPath: ${server.context-path}${management.context-path}/info
    healthCheckUrlPath: ${server.context-path}${management.context-path}/health
    metadata-map:
      management:
        context-path: ${server.context-path}${management.context-path}
  client:
    registryFetchIntervalSeconds: 5
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  context-path: /monitoring
  security:
    enabled: false

info:
  app:
    name: MCloud-uia
    desc: http://javaroad.me