server:
  port: 80
  servlet:
    context-path: /
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  application:
    name: mcloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: mcloud-registry
        uri: lb://mcloud-registry
        predicates:
        - Path=/registry/**
        filters:
          - Hystrix=registryCommand
          - RewritePath=/registry, /
      - id: mcloud-demo
        uri: lb://mcloud-demo
        predicates:
        - Path=/demo/**
        filters:
          - Hystrix=demoCommand
          - RewritePath=/demo, /
eureka:
  instance:
    appname: mcloud-gateway
    hostname: mcloud-apigw.example.com
    statusPageUrlPath: ${server.servlet.context-path}actuator/info
    healthCheckUrlPath: ${server.servlet.context-path}actuator/health
    metadata-map:
      management:
        server:
          port: ${server.port}
          context-path: ${server.servlet.context-path}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/