server:
  port: 8081
  servlet:
    context-path: /demo
logging:
  level:
    org.springframework.security: DEBUG
security:
  oauth2:
    resource:
      id: mcloud-demo
      user-info-uri: http://localhost:8443/auth/realms/mcloud/protocol/openid-connect/userinfo
      token-info-uri: http://localhost:8443/auth/realms/mcloud/protocol/openid-connect/token/introspect
      prefer-token-info: false
      jwt:
        key-uri: http://localhost:8443/auth/realms/mcloud
spring:
  application:
    name: mcloud-demo
  messages:
    basename: i18n/messages
eureka:
  instance:
    appname: mcloud-demo
    hostname: mcloud-demo.example.com
    statusPageUrlPath: ${server.servlet.context-path}/actuator/info
    healthCheckUrlPath: ${server.servlet.context-path}/actuator/health
    metadata-map:
      management:
        context-path: ${server.servlet.context-path}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

swagger:
  title: MCloud Demo
  description: http://javaroad.me
